// Code generated by commandgen; DO NOT EDIT.
// Spec: command_spec.yaml
// SpecHash: 5c17bb092056d7d30a60a87a8e29e54316451e219cf11f161fe2342c40af8d11

package commands

import (
	"github.com/spf13/cobra"
)

const generatedSpecHash = "5c17bb092056d7d30a60a87a8e29e54316451e219cf11f161fe2342c40af8d11"

// BuildMulticloudCommand builds the 'multicloud' command and its subcommands (generated)
func (recv *MulticloudCommands) BuildMulticloudCommand() *cobra.Command {
	root := &cobra.Command{
		Use:   "multicloud",
		Short: "Multi-cloud cost optimization and management",
		Long:  "Multi-cloud commands for cross-provider cost optimization, migration analysis,\nand unified reporting across AWS, Azure, and GCP.\n",
		RunE:  func(cmd *cobra.Command, args []string) error { return cmd.Help() },
	}

	root.PersistentFlags().StringSliceVar(&recv.flags.Providers, "providers", []string{}, "Cloud providers to include (aws,azure,gcp)")
	root.PersistentFlags().StringVar(&recv.flags.StartDate, "start-date", "", "Start date for analysis (YYYY-MM-DD)")
	root.PersistentFlags().StringVar(&recv.flags.EndDate, "end-date", "", "End date for analysis (YYYY-MM-DD)")
	root.PersistentFlags().StringVar(&recv.flags.OutputFormat, "format", "json", "Output format (json,yaml,table)")
	root.PersistentFlags().StringVar(&recv.flags.OutputFile, "output", "", "Output file path")
	root.PersistentFlags().StringVar(&recv.flags.ConfigFile, "config", "", "Multi-cloud configuration file")
	root_0 := &cobra.Command{
		Use:     "optimize",
		Short:   "Analyze cross-cloud optimization opportunities",
		Long:    "Analyze optimization opportunities across multiple cloud providers including\ncost arbitrage, migration opportunities, and resource consolidation.\n",
		Example: "costscope multicloud optimize --providers aws,azure\n",
		RunE:    recv.runOptimize,
	}

	root_0.Flags().StringSliceVar(&recv.flags.OptimizationTypes, "types", []string{}, "Optimization types (right_sizing,reserved_instances,spot_instances,cost_arbitrage,region_switching)")
	root_0.Flags().StringVar(&recv.flags.RiskTolerance, "risk-tolerance", "medium", "Risk tolerance level (low,medium,high)")
	root_0.Flags().Float64Var(&recv.flags.SavingsThreshold, "savings-threshold", 100.000000, "Minimum monthly savings threshold in USD")
	root_0.Flags().Float64Var(&recv.flags.AutoApprovalThreshold, "auto-approval-threshold", 1000.000000, "Auto-approval threshold in USD")
	root.AddCommand(root_0)
	root_1 := &cobra.Command{
		Use:   "compare",
		Short: "Compare costs across multiple cloud providers",
		Long:  "Compare costs across multiple cloud providers with normalized metrics\nand detailed breakdowns by service, region, and time period.\n",
		RunE:  recv.runCompare,
	}

	root_1.Flags().StringVar(&recv.flags.CurrencyNormalization, "currency", "USD", "Currency for cost normalization")
	root_1.Flags().StringVar(&recv.flags.AggregationLevel, "aggregation", "daily", "Aggregation level (hourly,daily,weekly,monthly)")
	root_1.Flags().BoolVar(&recv.flags.IncludeProviderBreakdown, "include-provider-breakdown", true, "Include provider breakdown")
	root.AddCommand(root_1)
	root_2 := &cobra.Command{
		Use:   "migrate",
		Short: "Estimate and plan cross-cloud migrations",
		Long:  "Estimate the costs and benefits of migrating workloads between cloud providers.\n",
		RunE:  recv.runMigrate,
	}

	root_2.Flags().StringVar(&recv.flags.SourceProvider, "source", "", "Source cloud provider")
	_ = root_2.MarkFlagRequired("source")
	root_2.Flags().StringVar(&recv.flags.TargetProvider, "target", "", "Target cloud provider")
	_ = root_2.MarkFlagRequired("target")
	root_2.Flags().StringVar(&recv.flags.ResourceSpecFile, "resources", "", "Resource specification file (YAML/JSON)")
	root.AddCommand(root_2)
	root_3 := &cobra.Command{
		Use:   "discover",
		Short: "Discover resources across multiple cloud providers",
		Long:  "Discover and inventory resources across all configured cloud providers.\n",
		RunE:  recv.runDiscover,
	}

	root_3.Flags().StringSliceVar(&recv.flags.ResourceTypes, "resource-types", []string{}, "Resource types to discover (compute,storage,database,network)")
	root_3.Flags().StringSliceVar(&recv.flags.Regions, "regions", []string{}, "Regions to scan")
	root_3.Flags().BoolVar(&recv.flags.IncludeMetadata, "include-metadata", false, "Include detailed resource metadata")
	root_3.Flags().BoolVar(&recv.flags.IncludeCosts, "include-costs", false, "Include cost information for resources")
	root.AddCommand(root_3)
	root_4 := &cobra.Command{
		Use:   "validate",
		Short: "Validate multi-cloud provider connections",
		Long:  "Validate credentials and connectivity for all configured cloud providers.\n",
		RunE:  recv.runValidate,
	}

	root.AddCommand(root_4)

	return root
}
