package integration

// Code generated by scripts/tools/gen-actions. DO NOT EDIT.

import (
	"embed"

	"gopkg.in/yaml.v3"
)

// reference embed to satisfy static analyzers
var _ embed.FS

//go:embed actions.yaml
var actionsYAML []byte

// BuildDefaultActionSpecs returns ActionSpecs loaded from the embedded DSL (actions.yaml).
// Generated at build-time to ensure single source of truth for CLI and API wiring.
func BuildDefaultActionSpecs() []ActionSpec {
	var dslDoc ActionDSL
	if err := yaml.Unmarshal(actionsYAML, &dslDoc); err != nil {
		return []ActionSpec{}
	}
	specs, err := (&dslDoc).ToActionSpecs()
	if err != nil {
		return []ActionSpec{}
	}
	return specs
}
