package commands

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"local/costscope/cmd/modules/analytics/types"
	"local/costscope/internal/core/analytics"
	"local/costscope/internal/core/config"
	"local/costscope/internal/core/config/precedence"
	focusanalysis "local/costscope/internal/core/focus/analysis"
	"local/costscope/internal/core/logging"

	"github.com/spf13/cobra"
)

// AnalyticsCommands manages analytics CLI commands
type AnalyticsCommands struct {
	logger  *logging.Logger
	service analytics.Service
}

// NewAnalyticsCommands creates a new analytics commands manager
func NewAnalyticsCommands(logger *logging.Logger, service analytics.Service) *AnalyticsCommands {
	return &AnalyticsCommands{
		logger:  logger,
		service: service,
	}
}

// BuildAnalyticsCommand builds the main analytics command
// Command graph is generated by zz_generated_command_builder.go.

// runAnalyze executes the analyze command
func (ac *AnalyticsCommands) runAnalyze(cmd *cobra.Command, args []string) error {
	ac.logger.Info("Starting cost analytics analysis")

	useFocus, _ := cmd.Flags().GetBool("use-focus-engine")
	if useFocus {
		// Attempt to load optional YAML once (cached globally inside env resolver); we only need Focus section
		yamlCfg := config.LoadOptionalYAML(ac.logger)
		var flagH *int
		var flagT *time.Duration
		if v, _ := cmd.Flags().GetInt("focus-forecast-days"); v > 0 {
			flagH = &v
		}
		if v, _ := cmd.Flags().GetDuration("focus-phase-timeout"); v > 0 {
			flagT = &v
		}
		selectH := func(cc *config.ConsolidatedConfig) *int {
			if cc == nil || cc.Focus.EngineForecastDaysDefault == 0 {
				return nil
			}
			return &cc.Focus.EngineForecastDaysDefault
		}
		selectT := func(cc *config.ConsolidatedConfig) *time.Duration {
			if cc == nil || cc.Focus.EnginePhaseTimeout == 0 {
				return nil
			}
			return &cc.Focus.EnginePhaseTimeout
		}
		resolvedH := precedence.ResolveInt(flagH, selectH(yamlCfg), "COSTSCOPE_FOCUS_ENGINE_FORECAST_DAYS", 30)
		precedence.LogResolved(ac.logger, "focus.engine.forecast_days", resolvedH)
		resolvedT := precedence.ResolveDuration(flagT, selectT(yamlCfg), "COSTSCOPE_FOCUS_ENGINE_TIMEOUT", 2*time.Second)
		precedence.LogResolved(ac.logger, "focus.engine.phase_timeout", resolvedT)

		eng := focusanalysis.NewEngine(ac.logger, nil)
		dataset, _ := cmd.Flags().GetString("table")
		base, err := eng.AnalyzeFOCUSDataset(dataset, focusanalysis.AnalysisOptions{ForecastDays: resolvedH.Value, ConfidenceLevel: 0.95, OutputFormat: "json"})
		if err != nil {
			return fmt.Errorf("focus analysis failed: %w", err)
		}
		extended := focusanalysis.RunExtendedPhases(context.Background(), eng, base, resolvedH.Value, 0.95, resolvedT.Value)
		base.Extended = extended
		b, _ := json.MarshalIndent(base, "", "  ")
		fmt.Println(string(b))
		return nil
	}

	opts, err := ac.parseAnalyticsOptions(cmd)
	if err != nil {
		return fmt.Errorf("failed to parse options: %w", err)
	}
	results, err := ac.service.Analyze(opts)
	if err != nil {
		return fmt.Errorf("analysis failed: %w", err)
	}
	return ac.displayResults("Analysis", results)
}

// runForecast executes the forecast command
func (ac *AnalyticsCommands) runForecast(cmd *cobra.Command, args []string) error {
	ac.logger.Info("Starting cost forecasting")

	opts, err := ac.parseAnalyticsOptions(cmd)
	if err != nil {
		return fmt.Errorf("failed to parse options: %w", err)
	}

	// Override ML settings for forecasting
	opts.EnableML = true

	forecastDays, _ := cmd.Flags().GetInt("forecast-days")
	opts.ForecastDays = forecastDays

	results, err := ac.service.Forecast(opts)
	if err != nil {
		return fmt.Errorf("forecasting failed: %w", err)
	}

	return ac.displayResults("Forecast", results)
}

// runCompare executes the compare command
func (ac *AnalyticsCommands) runCompare(cmd *cobra.Command, args []string) error {
	ac.logger.Info("Starting cost comparison")

	opts, err := ac.parseAnalyticsOptions(cmd)
	if err != nil {
		return fmt.Errorf("failed to parse options: %w", err)
	}

	comparePeriod, _ := cmd.Flags().GetString("compare-period")
	compareProviders, _ := cmd.Flags().GetStringSlice("compare-providers")

	results, err := ac.service.Compare(opts, comparePeriod, compareProviders)
	if err != nil {
		return fmt.Errorf("comparison failed: %w", err)
	}

	return ac.displayResults("Comparison", results)
}

// runExport executes the export command
func (ac *AnalyticsCommands) runExport(cmd *cobra.Command, args []string) error {
	ac.logger.Info("Starting analytics export")

	opts, err := ac.parseAnalyticsOptions(cmd)
	if err != nil {
		return fmt.Errorf("failed to parse options: %w", err)
	}

	format, _ := cmd.Flags().GetString("format")
	output, _ := cmd.Flags().GetString("output")

	exportPath, err := ac.service.Export(opts, format, output)
	if err != nil {
		return fmt.Errorf("export failed: %w", err)
	}

	fmt.Printf(" Results exported to: %s\n", exportPath)
	return nil
}

// parseAnalyticsOptions parses command flags into AnalyticsOptions
func (ac *AnalyticsCommands) parseAnalyticsOptions(cmd *cobra.Command) (*types.AnalyticsOptions, error) {
	opts := &types.AnalyticsOptions{}

	// Core options
	opts.TableName, _ = cmd.Flags().GetString("table")
	opts.Currency, _ = cmd.Flags().GetString("currency")
	opts.SortOrder, _ = cmd.Flags().GetString("sort-order")

	// Parse group by fields
	groupBy, _ := cmd.Flags().GetString("group-by")
	if groupBy != "" {
		opts.GroupByFields = strings.Split(groupBy, ",")
		for i := range opts.GroupByFields {
			opts.GroupByFields[i] = strings.TrimSpace(opts.GroupByFields[i])
		}
	}

	// Parse filters JSON
	filtersJSON, _ := cmd.Flags().GetString("filters")
	if filtersJSON != "" {
		if err := json.Unmarshal([]byte(filtersJSON), &opts.Filters); err != nil {
			return nil, fmt.Errorf("invalid filters JSON: %w", err)
		}
	}

	// Parse transformations JSON
	transformationsJSON, _ := cmd.Flags().GetString("transformations")
	if transformationsJSON != "" {
		if err := json.Unmarshal([]byte(transformationsJSON), &opts.TransformationRules); err != nil {
			return nil, fmt.Errorf("invalid transformations JSON: %w", err)
		}
	}

	// Feature toggles
	opts.EnableML, _ = cmd.Flags().GetBool("enable-ml")
	opts.EnableCaching, _ = cmd.Flags().GetBool("enable-caching")
	opts.StrictTypes, _ = cmd.Flags().GetBool("strict-types")
	opts.EnableParallel, _ = cmd.Flags().GetBool("enable-parallel")

	// Performance options
	opts.MaxConcurrency, _ = cmd.Flags().GetInt("max-concurrency")
	opts.CacheTTL, _ = cmd.Flags().GetDuration("cache-ttl")

	// ML options
	opts.ForecastDays, _ = cmd.Flags().GetInt("forecast-days")
	opts.EnableAnomalyDetection = true // Default enabled
	opts.EnableTrendAnalysis = true    // Default enabled
	opts.EnablePredictions = true      // Default enabled

	return opts, nil
}

// displayResults displays analytics results in a formatted way
func (ac *AnalyticsCommands) displayResults(operation string, results *types.AnalyticsResults) error {
	fmt.Printf("\n %s Results\n", operation)
	fmt.Printf("================\n")
	fmt.Printf("Timestamp: %s\n", results.Timestamp.Format(time.RFC3339))
	fmt.Printf("Table: %s\n", results.TableName)
	fmt.Printf("Filters Applied: %d\n", results.FiltersCount)

	if len(results.AnalysisResult) > 0 {
		fmt.Printf("\n Analysis Summary:\n")
		for key, value := range results.AnalysisResult {
			fmt.Printf("  %s: %v\n", key, value)
		}
	}

	if len(results.ForecastResult) > 0 {
		fmt.Printf("\n Forecast Results:\n")
		for key, value := range results.ForecastResult {
			fmt.Printf("  %s: %v\n", key, value)
		}
	}

	if len(results.ComparisonResult) > 0 {
		fmt.Printf("\n Comparison Results:\n")
		for key, value := range results.ComparisonResult {
			fmt.Printf("  %s: %v\n", key, value)
		}
	}

	fmt.Printf("\n")
	return nil
}
