// Code generated by commandgen; DO NOT EDIT.
// Spec: command_spec.yaml
// SpecHash: 34c0d9a18d1de48fc4495897ed8aae02d47afedc660fb133ab02ef95e0d66415

package commands

import (
	"github.com/spf13/cobra"
)

const generatedSpecHash = "34c0d9a18d1de48fc4495897ed8aae02d47afedc660fb133ab02ef95e0d66415"

// BuildAnalyticsCommand builds the 'analytics' command and its subcommands (generated)
func (recv *AnalyticsCommands) BuildAnalyticsCommand() *cobra.Command {
	root := &cobra.Command{
		Use:   "analytics",
		Short: "Advanced cost analytics and forecasting",
		Long:  "Advanced cost analytics with ML-powered forecasting, anomaly detection,\nand multi-cloud cost optimization capabilities.\n",
		RunE:  func(cmd *cobra.Command, args []string) error { return cmd.Help() },
	}

	root_0 := &cobra.Command{
		Use:   "analyze",
		Short: "Analyze cost data with advanced analytics",
		Long:  "Analyze cost data with type-safe filtering, advanced aggregations,\nand ML-powered insights. Supports multiple cloud providers and currencies.\n",
		RunE:  recv.runAnalyze,
	}

	root_0.Flags().String("table", "cost_data", "Table name for analysis")
	root_0.Flags().String("filters", "", "Type-safe filters in JSON format")
	root_0.Flags().String("currency", "USD", "Currency code for analysis")
	root_0.Flags().String("group-by", "", "Comma-separated fields to group by")
	root_0.Flags().String("sort-order", "desc", "Sort order (asc/desc)")
	root_0.Flags().String("transformations", "", "Data transformation rules in JSON format")
	root_0.Flags().Bool("enable-ml", true, "Enable ML forecasting features")
	root_0.Flags().Bool("enable-caching", true, "Enable performance caching")
	root_0.Flags().Bool("strict-types", false, "Enable strict type checking")
	root_0.Flags().Bool("enable-parallel", true, "Enable parallel processing")
	root_0.Flags().Int("max-concurrency", 10, "Maximum concurrent operations")
	root_0.Flags().Duration("cache-ttl", 0, "Cache TTL duration")
	root_0.Flags().Bool("use-focus-engine", false, "Use the FOCUS analysis engine (experimental)")
	root_0.Flags().Int("focus-forecast-days", 30, "Override focus engine forecast horizon (days); precedence flag>YAML>env>default(30)")
	root_0.Flags().Duration("focus-phase-timeout", 0, "Per-phase soft timeout for focus engine extended phases (e.g. 1500ms, 2s)")
	root.AddCommand(root_0)
	root_1 := &cobra.Command{
		Use:   "forecast",
		Short: "Generate ML-powered cost forecasts",
		Long:  "Generate cost forecasts using machine learning algorithms.\nIncludes trend analysis, seasonal patterns, and anomaly detection.\n",
		RunE:  recv.runForecast,
	}

	root_1.Flags().String("table", "cost_data", "Table name for analysis")
	root_1.Flags().String("filters", "", "Type-safe filters in JSON format")
	root_1.Flags().String("currency", "USD", "Currency code for analysis")
	root_1.Flags().String("group-by", "", "Comma-separated fields to group by")
	root_1.Flags().String("sort-order", "desc", "Sort order (asc/desc)")
	root_1.Flags().String("transformations", "", "Data transformation rules in JSON format")
	root_1.Flags().Int("forecast-days", 30, "Number of days to forecast")
	root_1.Flags().Bool("include-trends", true, "Include trend analysis")
	root_1.Flags().Bool("detect-anomalies", true, "Enable anomaly detection")
	root_1.Flags().Bool("enable-ml", true, "Enable ML forecasting features")
	root_1.Flags().Bool("enable-caching", true, "Enable performance caching")
	root_1.Flags().Bool("strict-types", false, "Enable strict type checking")
	root_1.Flags().Bool("enable-parallel", true, "Enable parallel processing")
	root_1.Flags().Int("max-concurrency", 10, "Maximum concurrent operations")
	root_1.Flags().Duration("cache-ttl", 0, "Cache TTL duration")
	root.AddCommand(root_1)
	root_2 := &cobra.Command{
		Use:   "compare",
		Short: "Compare costs across time periods or providers",
		Long:  "Compare costs across different time periods, cloud providers,\nor resource configurations. Generate detailed comparison reports.\n",
		RunE:  recv.runCompare,
	}

	root_2.Flags().String("table", "cost_data", "Table name for analysis")
	root_2.Flags().String("filters", "", "Type-safe filters in JSON format")
	root_2.Flags().String("currency", "USD", "Currency code for analysis")
	root_2.Flags().String("group-by", "", "Comma-separated fields to group by")
	root_2.Flags().String("sort-order", "desc", "Sort order (asc/desc)")
	root_2.Flags().String("transformations", "", "Data transformation rules in JSON format")
	root_2.Flags().String("compare-period", "", "Period to compare with (e.g., 'previous-month')")
	root_2.Flags().StringSlice("compare-providers", []string{}, "Providers to compare")
	root_2.Flags().Bool("enable-ml", true, "Enable ML forecasting features")
	root_2.Flags().Bool("enable-caching", true, "Enable performance caching")
	root_2.Flags().Bool("strict-types", false, "Enable strict type checking")
	root_2.Flags().Bool("enable-parallel", true, "Enable parallel processing")
	root_2.Flags().Int("max-concurrency", 10, "Maximum concurrent operations")
	root_2.Flags().Duration("cache-ttl", 0, "Cache TTL duration")
	root.AddCommand(root_2)
	root_3 := &cobra.Command{
		Use:   "export",
		Short: "Export analytics results to various formats",
		Long:  "Export analytics results to JSON, CSV, or other formats.\nSupports filtering and custom output formatting.\n",
		RunE:  recv.runExport,
	}

	root_3.Flags().String("table", "cost_data", "Table name for analysis")
	root_3.Flags().String("filters", "", "Type-safe filters in JSON format")
	root_3.Flags().String("currency", "USD", "Currency code for analysis")
	root_3.Flags().String("group-by", "", "Comma-separated fields to group by")
	root_3.Flags().String("sort-order", "desc", "Sort order (asc/desc)")
	root_3.Flags().String("transformations", "", "Data transformation rules in JSON format")
	root_3.Flags().String("format", "json", "Export format (json, csv, yaml)")
	root_3.Flags().String("output", "", "Output file path")
	root_3.Flags().Bool("enable-ml", true, "Enable ML forecasting features")
	root_3.Flags().Bool("enable-caching", true, "Enable performance caching")
	root_3.Flags().Bool("strict-types", false, "Enable strict type checking")
	root_3.Flags().Bool("enable-parallel", true, "Enable parallel processing")
	root_3.Flags().Int("max-concurrency", 10, "Maximum concurrent operations")
	root_3.Flags().Duration("cache-ttl", 0, "Cache TTL duration")
	root.AddCommand(root_3)

	return root
}
