package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/costscope/costscope/internal/testutil"
)

const providerReadmeTemplate = `# {{TITLE}} Provider (Scaffold)

Status: WIP (generated by gen-provider)

TODO:
- [ ] Describe authentication / credentials fields
- [ ] Implement ValidateCredentials (actual auth logic)
- [ ] Implement GetProviderInfo (populate capabilities / metadata)
- [ ] Implement GetCostData / GetResourceData (streaming pagination)
- [ ] Flesh out FOCUS conversion mapper (conversion/{{name}}/mapper.go)
- [ ] Add golden dataset & parity/invariants tests
- [ ] Add quickstart doc (docs/providers/{{name}}_quickstart.md)

Testing (initial stubs):
	go test ./internal/providers/{{name}} -count=1
	go test ./internal/core/focus/conversion/{{name}} -count=1
`

const providerDocTemplate = `// Package {{name}} implements the {{TITLE}} cloud provider integration.
//
// Generated scaffold. Fill in auth, rate limiting, and data retrieval details.
package {{name}}`

const providerConfigTemplate = `package {{name}}

import "github.com/costscope/costscope/internal/providers/types"

// {{Title}}Config extends ProviderConfig with {{TITLE}} specific settings (extend as needed).
type {{Title}}Config struct {
	Region string ` + "`json:\"region,omitempty\" yaml:\"region,omitempty\"`" + `
}

// ToProviderConfig materializes a types.ProviderConfig for registry / manager usage.
func (c *{{Title}}Config) ToProviderConfig() *types.ProviderConfig {
	return &types.ProviderConfig{
		Name:        "{{name}}",
		Type:        types.ProviderType("{{name}}"),
		Credentials: map[string]string{}, // TODO: load from env/secret manager
		Settings:    map[string]interface{}{"region": c.Region},
		Regions:     []string{},
	}
}
`

const providerMainTemplate = `package {{name}}

import (
	"context"
	"errors"
	"github.com/costscope/costscope/internal/core/logging"
	"github.com/costscope/costscope/internal/providers/types"
)

// Err{{Title}}NotImplemented indicates unimplemented stub logic.
var Err{{Title}}NotImplemented = errors.New("{{name}} provider functionality not implemented")

// Provider implements types.CloudProvider for {{TITLE}}.
type Provider struct {
	logger *logging.Logger
	cfg    *types.ProviderConfig
}

// New creates a new {{TITLE}} provider instance.
func New(cfg *types.ProviderConfig, logger *logging.Logger) *Provider {
	if logger == nil { logger = logging.NewLogger(logging.LevelInfo) }
	return &Provider{cfg: cfg, logger: logger}
}

// ValidateCredentials validates supplied credentials (stub: accept all for now).
func (p *Provider) ValidateCredentials(ctx context.Context, creds map[string]string) error {
	if p.logger != nil { p.logger.Info("{{name}}: ValidateCredentials (stub)") }
	return nil
}

// GetProviderInfo returns high-level metadata (stub values).
func (p *Provider) GetProviderInfo(ctx context.Context) (types.ProviderInfo, error) {
	return types.ProviderInfo{
		Name:             p.GetName(),
		Type:             p.GetType(),
		Version:          "v0.0.0",
		SupportedRegions: p.GetSupportedRegions(),
		Capabilities:     []string{"cost-data", "resource-data"},
		Metadata:         map[string]string{"stub": "true"},
	}, nil
}

// GetCostData retrieves cost records (stub returns empty slice).
func (p *Provider) GetCostData(ctx context.Context, params types.CostDataParams) ([]types.CostRecord, error) {
	return []types.CostRecord{}, Err{{Title}}NotImplemented
}

// GetResourceData retrieves resource inventory (stub returns empty slice).
func (p *Provider) GetResourceData(ctx context.Context, params types.ResourceDataParams) ([]types.ResourceRecord, error) {
	return []types.ResourceRecord{}, Err{{Title}}NotImplemented
}

func (p *Provider) GetName() string { return "{{name}}" }
// Name implements registry.Provider compatibility.
func (p *Provider) Name() string { return p.GetName() }
func (p *Provider) GetType() types.ProviderType { return types.ProviderType("{{name}}") }
func (p *Provider) GetSupportedRegions() []string { return []string{} }
`

const providerRegisterTemplate = `package {{name}}

import (
	"github.com/costscope/costscope/internal/core/logging"
	"github.com/costscope/costscope/internal/providers/registry"
	"github.com/costscope/costscope/internal/providers/types"
)

// Auto-register minimal instance for registry discovery (expand as needed).
func init() {
	registry.Register("{{name}}", func(opts ...interface{}) (registry.Provider, error) {
		cfg := &types.ProviderConfig{Name: "{{name}}", Type: types.ProviderType("{{name}}")}
		return New(cfg, logging.NewLogger(logging.LevelError)), nil
	})
}
`

const convReadmeTemplate = `# {{TITLE}} FOCUS Converter (Scaffold)

Generated stub.

Next steps:
- Define input schema (headers.go)
- Implement streaming parser in converter.go
- Implement field mapping in mapper.go
- Add invariants & parity tests
`

const convHeadersTemplate = `package {{name}}

// ExpectedHeaders defines ordered list of input CSV headers (edit as needed).
var ExpectedHeaders = []string{
    // TODO: add real headers
}
`

const convMapperTemplate = `package {{name}}

import (
    "github.com/costscope/costscope/internal/core/focus/conversion/common"
    "github.com/costscope/costscope/internal/core/focus/conversion/universal"
)

// recordMapper implements universal.RecordMapper.
type recordMapper struct { path string }

func NewRecordMapper(path string) universal.RecordMapper { return &recordMapper{path: path} }

func (m *recordMapper) Map(raw *common.RawRecord, out *common.MutableFocusRecord) error {
    // TODO: map fields from raw.Fields to out.Set* methods
    return nil
}
`

const convConverterTemplate = `package {{name}}

import (
    "context"
    "io"
    "github.com/costscope/costscope/internal/core/focus/conversion/universal"
)

// Converter implements streaming conversion for {{TITLE}} (stub).
type Converter struct { opts universal.Options }

func NewConverter(opts universal.Options) *Converter { return &Converter{opts: opts} }

func (c *Converter) ConvertStream(ctx context.Context, r io.Reader, sink universal.RecordSink) error {
    return universal.ErrNotImplemented
}
`

const convTestTemplate = `package {{name}}_test

import (
    "bytes"
    "context"
    "testing"
    "github.com/costscope/costscope/internal/core/focus/conversion/{{name}}"
    "github.com/costscope/costscope/internal/core/focus/conversion/universal"
)

func Test{{Title}}ConverterStub(t *testing.T) {
    c := {{name}}.NewConverter(universal.Options{})
    input := bytes.NewBufferString("colA,colB\n1,2\n")
    sink := &universal.MemorySink{}
    if err := c.ConvertStream(context.Background(), input, sink); err == nil {
        t.Fatalf("expected error for stub converter")
    }
}
`

func main() {
	name := flag.String("name", "", "provider name (lower-case)")
	force := flag.Bool("force", false, "overwrite existing scaffold files if safe")
	dryRun := flag.Bool("dry-run", false, "print actions only")
	flag.Parse()
	if *name == "" {
		fatal(errors.New("-name is required"))
	}
	if !regexp.MustCompile(`^[a-z0-9_]+$`).MatchString(*name) {
		fatal(fmt.Errorf("invalid provider name: %s", *name))
	}
	title := toTitle(*name)
	root, err := testutil.RepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "unable to locate repo root: %v\n", err)
		os.Exit(1)
	}
	// Paths
	pDir := filepath.Join(root, "internal", "providers", *name)
	cDir := filepath.Join(root, "internal", "core", "focus", "conversion", *name)
	files := map[string]string{
		filepath.Join(pDir, "README.md"):         strings.ReplaceAll(repl(providerReadmeTemplate, *name, title), "{{TITLE}}", title),
		filepath.Join(pDir, "doc.go"):            repl(providerDocTemplate, *name, title),
		filepath.Join(pDir, "config.go"):         repl(providerConfigTemplate, *name, title),
		filepath.Join(pDir, "provider.go"):       repl(providerMainTemplate, *name, title),
		filepath.Join(pDir, "register.go"):       repl(providerRegisterTemplate, *name, title),
		filepath.Join(pDir, "provider_test.go"):  testProviderTemplate(*name),
		filepath.Join(cDir, "README.md"):         strings.ReplaceAll(repl(convReadmeTemplate, *name, title), "{{TITLE}}", title),
		filepath.Join(cDir, "headers.go"):        repl(convHeadersTemplate, *name, title),
		filepath.Join(cDir, "mapper.go"):         repl(convMapperTemplate, *name, title),
		filepath.Join(cDir, "converter.go"):      repl(convConverterTemplate, *name, title),
		filepath.Join(cDir, "converter_test.go"): repl(convTestTemplate, *name, title),
	}
	// Actions summary
	for path := range files {
		if *dryRun {
			fmt.Println("CREATE", path)
			continue
		}
		// #nosec G301 -- directories are non-sensitive scaffolds; 0750 acceptable
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			fatal(err)
		}
		if _, statErr := os.Stat(path); statErr == nil && !*force {
			fmt.Printf("SKIP (exists) %s\n", path)
			continue
		}
		if err := os.WriteFile(path, []byte(files[path]), 0o600); err != nil {
			fatal(err)
		}
		fmt.Println("WROTE", path)
	}
	if *dryRun {
		return
	}
	if err := ensureManagerImport(root, *name); err != nil {
		fatal(err)
	}
	fmt.Printf("gen-provider: scaffold complete for '%s'\n", *name)
}

func testProviderTemplate(name string) string {
	// Use %[1]s to reuse provider name; escape %% verbs for runtime test formatting.
	return fmt.Sprintf(`package %[1]s_test

import (
	"context"
	"testing"
	"github.com/costscope/costscope/internal/core/logging"
	"github.com/costscope/costscope/internal/providers/%[1]s"
	"github.com/costscope/costscope/internal/providers/types"
)

func TestProviderBasic(t *testing.T) {
	p := %[1]s.New(&types.ProviderConfig{Name: "%[1]s", Type: "%[1]s"}, logging.NewLogger(logging.LevelError))
	if p.GetName() != "%[1]s" { t.Fatalf("expected name %%s", "%[1]s") }
	if p.GetType() != types.ProviderType("%[1]s") { t.Fatalf("expected type %%s", "%[1]s") }
	if err := p.ValidateCredentials(context.Background(), map[string]string{}); err != nil { t.Fatalf("ValidateCredentials: %%v", err) }
	if _, err := p.GetProviderInfo(context.Background()); err != nil { t.Fatalf("GetProviderInfo: %%v", err) }
}
`, name)
}

func repl(tpl, name, title string) string {
	out := strings.ReplaceAll(tpl, "{{name}}", name)
	out = strings.ReplaceAll(out, "{{Title}}", title)
	out = strings.ReplaceAll(out, "{{TITLE}}", title)
	return out
}

func toTitle(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func ensureManagerImport(root, name string) error {
	mgrPath := filepath.Join(root, "internal", "providers", "manager.go")
	// #nosec G304 -- controlled internal path, not user supplied
	b, err := os.ReadFile(mgrPath)
	if err != nil {
		return err
	}
	content := string(b)
	line := fmt.Sprintf("\t_ \"github.com/costscope/costscope/internal/providers/%s\"   // side-effect registration", name)
	if strings.Contains(content, line) {
		return nil
	}
	// Insert after last existing side-effect provider import
	lines := strings.Split(content, "\n")
	lastIdx := -1
	for i, l := range lines {
		if strings.Contains(l, "internal/providers/") && strings.Contains(l, "_ \"") {
			lastIdx = i
		}
	}
	if lastIdx == -1 {
		return errors.New("could not locate import block to patch in manager.go")
	}
	// Insert new line after lastIdx
	newLines := append([]string{}, lines[:lastIdx+1]...)
	newLines = append(newLines, line)
	newLines = append(newLines, lines[lastIdx+1:]...)
	if err := os.WriteFile(mgrPath, []byte(strings.Join(newLines, "\n")), 0o600); err != nil {
		return err
	}
	fmt.Println("UPDATED", mgrPath)
	return nil
}

func fatal(err error) { fmt.Fprintf(os.Stderr, "gen-provider: %v\n", err); os.Exit(2) }
