package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	integration "local/costscope/cmd/modules/integration"
)

// Minimal validator/codegen stub for Integration Action DSL
// P1 scope: validate uniqueness and flag collisions; print JSON skeleton or write files in future phases.

type ValidationReport struct {
	TotalSpecs    int      `json:"total_specs"`
	DuplicateIDs  []string `json:"duplicate_ids,omitempty"`
	FlagConflicts []string `json:"flag_conflicts,omitempty"`
}

func main() {
	lintOnly := flag.Bool("lint-only", false, "run validations only (no generation)")
	out := flag.String("out", "-", "output path for generated artifacts (ignored when --lint-only)")
	yamlPath := flag.String("yaml", "cmd/modules/integration/actions.yaml", "path to actions YAML DSL")
	genGo := flag.String("gen-go", "cmd/modules/integration/generated_actions.go", "path to write generated Go specs file")
	emit := flag.String("emit", "embedded", "spec emission mode: embedded|static (default embedded)")
	genAPI := flag.Bool("gen-api", true, "generate API artifacts (handlers stubs, OpenAPI paths) when applicable")
	flag.Parse()

	rep := validate(*yamlPath)
	if *lintOnly {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		_ = enc.Encode(rep)
		if len(rep.DuplicateIDs) > 0 || len(rep.FlagConflicts) > 0 {
			os.Exit(2)
		}
		return
	}
	// Generate Go file from YAML DSL for BuildDefaultActionSpecs
	var genErr error
	switch *emit {
	case "embedded":
		genErr = generateFromYAML(*yamlPath, *genGo)
	case "static":
		genErr = generateStaticSpecs(*yamlPath, *genGo)
	default:
		fmt.Fprintf(os.Stderr, "gen-actions: invalid --emit=%s (use embedded|static)\n", *emit)
		os.Exit(2)
	}
	if genErr != nil {
		fmt.Fprintf(os.Stderr, "gen-actions: generation failed: %v\n", genErr)
		os.Exit(1)
	}
	// Phase 2: emit API handler stubs and OpenAPI path fragments
	if *genAPI {
		if err := generateAPIArtifacts(*yamlPath); err != nil {
			fmt.Fprintf(os.Stderr, "gen-actions: api generation failed: %v\n", err)
			os.Exit(1)
		}
	}
	if *out != "-" {
		b, _ := json.MarshalIndent(rep, "", "  ")
		_ = os.WriteFile(*out, b, 0o600)
	}
	fmt.Printf("gen-actions: validations OK; generated %s from %s\n", *genGo, *yamlPath)
}

func validate(yamlPath string) ValidationReport {
	dsl, err := integration.LoadActionDSL(yamlPath)
	if err != nil {
		return ValidationReport{TotalSpecs: 0, DuplicateIDs: []string{"DSL load error: " + err.Error()}}
	}
	if err := dsl.Validate(); err != nil {
		// surface structural errors under DuplicateIDs to make CI failure obvious without changing report schema
		return ValidationReport{TotalSpecs: 0, DuplicateIDs: []string{"DSL structural validation failed: " + err.Error()}}
	}
	specs, err := dsl.ToActionSpecs()
	if err != nil {
		return ValidationReport{TotalSpecs: 0, DuplicateIDs: []string{"DSL convert error: " + err.Error()}}
	}
	// ID uniqueness
	seen := map[string]struct{}{}
	var dups []string
	for _, s := range specs {
		if _, ok := seen[s.ID]; ok {
			dups = append(dups, s.ID)
		}
		seen[s.ID] = struct{}{}
	}
	// Flag conflicts: within a single category+use path, ensure flag names are unique across specs that share same path
	pathFlags := map[string]map[string]struct{}{}
	var conflicts []string
	for _, s := range specs {
		path := strings.Join(append(append([]string{s.Category}, s.Parents...), s.Use), " ")
		if _, ok := pathFlags[path]; !ok {
			pathFlags[path] = map[string]struct{}{}
		}
		for _, f := range s.Flags {
			if _, ok := pathFlags[path][f.Name]; ok {
				conflicts = append(conflicts, fmt.Sprintf("%s: flag '%s' duplicated", path, f.Name))
			}
			pathFlags[path][f.Name] = struct{}{}
		}
	}
	return ValidationReport{TotalSpecs: len(specs), DuplicateIDs: dups, FlagConflicts: conflicts}
}

// generateFromYAML renders a tiny Go file implementing BuildDefaultActionSpecs() that loads YAML at runtime.
// Later we can switch to full static generation if needed.
func generateFromYAML(yamlPath, outGo string) error {
	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(outGo), 0o750); err != nil { // restrict perms per gosec G301
		return err
	}
	const tpl = `package integration

// Code generated by scripts/tools/gen-actions. DO NOT EDIT.

import (
	"embed"
	"gopkg.in/yaml.v3"
)

// reference embed to satisfy static analyzers
var _ embed.FS

//go:embed actions.yaml
var actionsYAML []byte

// BuildDefaultActionSpecs returns ActionSpecs loaded from the embedded DSL (actions.yaml).
// Generated at build-time to ensure single source of truth for CLI and API wiring.
func BuildDefaultActionSpecs() []ActionSpec {
	var dslDoc ActionDSL
	if err := yaml.Unmarshal(actionsYAML, &dslDoc); err != nil {
		return []ActionSpec{}
	}
	specs, err := (&dslDoc).ToActionSpecs()
	if err != nil {
		return []ActionSpec{}
	}
	return specs
}
`
	// #nosec G304 -- output path is provided by trusted build tooling (Makefile/CI), not user input
	f, err := os.OpenFile(outGo, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }() // errcheck: ignore close error on best-effort write
	t := template.Must(template.New("gen").Parse(tpl))
	data := map[string]string{"YAMLPath": yamlPath}
	return t.Execute(f, data)
}

// escape backticks and backslashes for Go raw strings
func esc(in string) string { return strings.ReplaceAll(strings.ReplaceAll(in, "\\", "\\\\"), "`", "'") }

// writeDefaultString emits a string default.
func writeDefaultString(buf *bytes.Buffer, f integration.FlagSpec) {
	if v, ok := f.Default.(string); ok && v != "" {
		fmt.Fprintf(buf, ", Default: `%s`", esc(v))
	}
}

// writeDefaultBool emits a bool default.
func writeDefaultBool(buf *bytes.Buffer, f integration.FlagSpec) {
	if v, ok := f.Default.(bool); ok && v {
		buf.WriteString(", Default: true")
	}
}

// writeDefaultInt emits an int-like default.
func writeDefaultInt(buf *bytes.Buffer, f integration.FlagSpec) {
	switch v := f.Default.(type) {
	case int:
		if v != 0 {
			fmt.Fprintf(buf, ", Default: %d", v)
		}
	case int64:
		if v != 0 {
			fmt.Fprintf(buf, ", Default: %d", v)
		}
	case float64:
		if v != 0 {
			fmt.Fprintf(buf, ", Default: %d", int(v))
		}
	}
}

// writeDefaultFloat64 emits a float64 default.
func writeDefaultFloat64(buf *bytes.Buffer, f integration.FlagSpec) {
	if v, ok := f.Default.(float64); ok && v != 0 {
		fmt.Fprintf(buf, ", Default: %v", v)
	}
}

// writeDefaultStringSlice emits a []string default.
func writeDefaultStringSlice(buf *bytes.Buffer, f integration.FlagSpec) {
	switch vv := f.Default.(type) {
	case []string:
		if len(vv) == 0 {
			return
		}
		buf.WriteString(", Default: []string{")
		for i, sv := range vv {
			if i > 0 {
				buf.WriteString(",")
			}
			fmt.Fprintf(buf, "`%s`", esc(sv))
		}
		buf.WriteString("}")
	case []any:
		if len(vv) == 0 {
			return
		}
		buf.WriteString(", Default: []string{")
		for i, it := range vv {
			if i > 0 {
				buf.WriteString(",")
			}
			fmt.Fprintf(buf, "`%s`", esc(fmt.Sprint(it)))
		}
		buf.WriteString("}")
	}
}

// writeDefaultMapStringString emits a map[string]string default.
func writeDefaultMapStringString(buf *bytes.Buffer, f integration.FlagSpec) {
	if mm, ok := f.Default.(map[string]string); ok && len(mm) > 0 {
		buf.WriteString(", Default: map[string]string{")
		keys := make([]string, 0, len(mm))
		for k := range mm {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				buf.WriteString(",")
			}
			fmt.Fprintf(buf, "`%s`:`%s`", esc(k), esc(mm[k]))
		}
		buf.WriteString("}")
	}
}

// writeDefault emits Default: ... for a given flag, when applicable.
func writeDefault(buf *bytes.Buffer, f integration.FlagSpec) {
	switch f.Type {
	case "string":
		writeDefaultString(buf, f)
	case "bool":
		writeDefaultBool(buf, f)
	case "int":
		writeDefaultInt(buf, f)
	case "float64":
		writeDefaultFloat64(buf, f)
	case "duration":
		if v, ok := f.Default.(time.Duration); ok && v != 0 {
			fmt.Fprintf(buf, ", Default: time.Duration(%d)", int64(v))
		}
	case "stringSlice":
		writeDefaultStringSlice(buf, f)
	case "stringToString":
		writeDefaultMapStringString(buf, f)
	}
}

// writeFlag emits a single FlagSpec struct literal.
func writeFlag(buf *bytes.Buffer, f integration.FlagSpec) {
	buf.WriteString("\t\t{")
	fmt.Fprintf(buf, "Name: `%s`, Type: `%s`, Usage: `%s`", esc(f.Name), esc(f.Type), esc(f.Usage))
	if f.Shorthand != "" {
		fmt.Fprintf(buf, ", Shorthand: `%s`", esc(f.Shorthand))
	}
	if f.Required {
		buf.WriteString(", Required: true")
	}
	if f.Hidden {
		buf.WriteString(", Hidden: true")
	}
	if f.Deprecated != "" {
		fmt.Fprintf(buf, ", Deprecated: `%s`", esc(f.Deprecated))
	}
	if f.Env != "" {
		fmt.Fprintf(buf, ", Env: `%s`", esc(f.Env))
	}
	if len(f.Choices) > 0 {
		buf.WriteString(", Choices: []string{")
		for i, c := range f.Choices {
			if i > 0 {
				buf.WriteString(",")
			}
			fmt.Fprintf(buf, "`%s`", esc(c))
		}
		buf.WriteString("}")
	}
	writeDefault(buf, f)
	buf.WriteString("},\n")
}

// writeActionSpec emits a single ActionSpec struct literal.
func writeActionSpec(buf *bytes.Buffer, s integration.ActionSpec) {
	buf.WriteString("{\n")
	fmt.Fprintf(buf, "\tID: `%s`,\n", esc(s.ID))
	fmt.Fprintf(buf, "\tCategory: `%s`,\n", esc(s.Category))
	fmt.Fprintf(buf, "\tUse: `%s`,\n", esc(s.Use))
	fmt.Fprintf(buf, "\tShort: `%s`,\n", esc(s.Short))
	if s.Long != "" {
		fmt.Fprintf(buf, "\tLong: `%s`,\n", esc(s.Long))
	}
	if s.Example != "" {
		fmt.Fprintf(buf, "\tExample: `%s`,\n", esc(s.Example))
	}
	if len(s.Parents) > 0 {
		buf.WriteString("\tParents: []string{")
		for i, p := range s.Parents {
			if i > 0 {
				buf.WriteString(",")
			}
			fmt.Fprintf(buf, "`%s`", esc(p))
		}
		buf.WriteString("},\n")
	}
	if s.Group {
		buf.WriteString("\tGroup: true,\n")
	}
	if s.FeatureGate != "" {
		fmt.Fprintf(buf, "\tFeatureGate: `%s`,\n", esc(s.FeatureGate))
	}
	if len(s.Flags) > 0 {
		buf.WriteString("\tFlags: []FlagSpec{\n")
		for _, f := range s.Flags {
			writeFlag(buf, f)
		}
		buf.WriteString("\t},\n")
	}
	if len(s.MutuallyExclusive) > 0 {
		buf.WriteString("\tMutuallyExclusive: [][]string{")
		for gi, grp := range s.MutuallyExclusive {
			if gi > 0 {
				buf.WriteString(",")
			}
			buf.WriteString("{")
			for i, n := range grp {
				if i > 0 {
					buf.WriteString(",")
				}
				fmt.Fprintf(buf, "`%s`", esc(n))
			}
			buf.WriteString("}")
		}
		buf.WriteString("},\n")
	}
	if len(s.AtLeastOneOf) > 0 {
		buf.WriteString("\tAtLeastOneOf: []string{")
		for i, n := range s.AtLeastOneOf {
			if i > 0 {
				buf.WriteString(",")
			}
			fmt.Fprintf(buf, "`%s`", esc(n))
		}
		buf.WriteString("},\n")
	}
	buf.WriteString("},\n")
}

// generateStaticSpecs renders a Go file with var defaultSpecs = []ActionSpec{...} and BuildDefaultActionSpecs() returning it.
func generateStaticSpecs(yamlPath, outGo string) error {
	if err := os.MkdirAll(filepath.Dir(outGo), 0o750); err != nil { // restrict perms per gosec G301
		return err
	}
	dsl, err := integration.LoadActionDSL(yamlPath)
	if err != nil {
		return err
	}
	if err := dsl.Validate(); err != nil {
		return err
	}
	specs, err := dsl.ToActionSpecs()
	if err != nil {
		return err
	}
	sort.Slice(specs, func(i, j int) bool { return specs[i].ID < specs[j].ID })
	needTime := false
	for _, s := range specs {
		for _, f := range s.Flags {
			if f.Type == "duration" {
				if v, ok := f.Default.(time.Duration); ok && v != 0 {
					needTime = true
					break
				}
			}
		}
		if needTime {
			break
		}
	}
	var buf bytes.Buffer
	buf.WriteString("package integration\n\n// Code generated by scripts/tools/gen-actions (static). DO NOT EDIT.\n\n")
	if needTime {
		buf.WriteString("import \"time\"\n\n")
	}
	buf.WriteString("// defaultSpecs holds statically generated ActionSpecs (no YAML parsing at runtime).\n")
	buf.WriteString("var defaultSpecs = []ActionSpec{\n")
	for _, s := range specs {
		writeActionSpec(&buf, s)
	}
	buf.WriteString("}\n\n")
	buf.WriteString("// BuildDefaultActionSpecs returns the statically generated defaultSpecs.\n")
	buf.WriteString("func BuildDefaultActionSpecs() []ActionSpec { return defaultSpecs }\n")
	return os.WriteFile(outGo, buf.Bytes(), 0o600)
}

// generateAPIArtifacts writes handler stubs and an OpenAPI fragment with minimal paths.
func generateAPIArtifacts(yamlPath string) error {
	dsl, err := integration.LoadActionDSL(yamlPath)
	if err != nil {
		return err
	}
	specs, err := dsl.ToActionSpecs()
	if err != nil {
		return err
	}
	for _, s := range specs {
		if s.Group {
			continue
		}
		dir := filepath.Join("internal/api/handlers/integration", s.Category)
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return err
		}
		file := filepath.Join(dir, s.Use+".go")
		if _, err := os.Stat(file); err == nil {
			continue
		}
		// package name = category; keep stubs isolated
		stub := fmt.Sprintf(`package %s

import (
	"net/http"
	"github.com/gin-gonic/gin"
	"local/costscope/internal/core/logging"
)

type %sHandler struct { logger *logging.Logger }

func New%sHandler(logger *logging.Logger) *%sHandler { return &%sHandler{logger: logger} }

// Handle%s is a generated stub for integration action %s (category=%s)
func (h *%sHandler) Handle%s(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, gin.H{"status":"not_implemented","action_id":"%s"})
}
`, s.Category, exportName(s.Use), exportName(s.Use), exportName(s.Use), exportName(s.Use), exportName(s.Use), s.ID, s.Category, exportName(s.Use), exportName(s.Use), s.ID)
		if err := os.WriteFile(file, []byte(stub), 0o600); err != nil {
			return err
		}
	}
	fragDir := "internal/api/docs"
	if err := os.MkdirAll(fragDir, 0o750); err != nil {
		return err
	}
	fragPath := filepath.Join(fragDir, "integration.paths.fragment.yaml")
	var frag bytes.Buffer
	frag.WriteString("# Auto-generated minimal integration paths (placeholders)\npaths:\n")
	for _, s := range specs {
		if s.Group {
			continue
		}
		// include parent group segments in path to avoid collisions
		segments := append([]string{s.Category}, append(s.Parents, s.Use)...)
		p := fmt.Sprintf("  /api/v1/integration/%s:\n    post:\n      summary: Integration action %s\n      tags: [Integration]\n      responses:\n        '501': { description: Not Implemented }\n", strings.Join(segments, "/"), s.ID)
		frag.WriteString(p)
	}
	return os.WriteFile(fragPath, frag.Bytes(), 0o600)
}

// exportName capitalizes first rune of a name
func exportName(name string) string {
	if name == "" {
		return "X"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}
