#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/generate-enterprise-stubs.sh <feature_label> <package_dir> <type_name> [interface_name]

Arguments:
  feature_label  Short metric / label id (e.g. streaming_engine)
  package_dir    Go package directory (e.g. internal/core/streaming)
  type_name      Implementation type (e.g. EnterpriseStreamingEngine)
  interface_name Optional interface this type implements (adds compile-time assert)

Creates two files if they do not already exist:
  <package_dir>/<snake_feature>_stub.go        (//go:build !enterprise)
  <package_dir>/<snake_feature>_enterprise.go  (//go:build enterprise) – minimal scaffold

Stub file uses unified enterprise metrics/helpers (enterprise.Observe* + DisabledError).
Real file is a placeholder prompting implementation. Existing files are never overwritten.

Environment:
  LICENSE_HEADER=false  (suppress header comment)

Examples:
  scripts/generate-enterprise-stubs.sh streaming_engine internal/core/streaming EnterpriseStreamingEngine
  scripts/generate-enterprise-stubs.sh connection_manager internal/database EnterpriseConnectionManager ConnectionManager

EOF
}

if [[ $# -lt 3 ]]; then
  usage >&2; exit 1
fi

FEATURE_LABEL="$1"         # streaming_engine
PKG_DIR="$2"              # internal/core/streaming
TYPE_NAME="$3"            # EnterpriseStreamingEngine
IFACE_NAME="${4:-}"       # optional

if [[ ! -d "$PKG_DIR" ]]; then
  echo "Package dir $PKG_DIR does not exist" >&2
  exit 2
fi

snake() {
  echo "$1" | sed -E 's/([a-z0-9])([A-Z])|-/\1_\2/g' | tr '[:upper:]' '[:lower:]' | sed 's/__/_/g'
}

SNAKE_FEATURE="$(snake "$FEATURE_LABEL")"
STUB_FILE="$PKG_DIR/${SNAKE_FEATURE}_stub.go"
REAL_FILE="$PKG_DIR/${SNAKE_FEATURE}_enterprise.go"

header() {
  if [[ "${LICENSE_HEADER:-true}" == "true" ]]; then
    cat <<'H'
// Code generated by generate-enterprise-stubs.sh; DO NOT EDIT.
// This file is a scaffold for enterprise-gated functionality.
H
  fi
}

if [[ -f "$STUB_FILE" ]]; then
  echo "Skip (exists): $STUB_FILE" >&2
else
  echo "Creating stub: $STUB_FILE" >&2
  {
    echo "//go:build !enterprise"; echo; header
    echo "package $(basename "$PKG_DIR")"; echo
    cat <<STUB
import (
    "context"
    "local/costscope/internal/core/enterprise"
)

// ${TYPE_NAME} stub (non-enterprise build).
type ${TYPE_NAME} struct{}

// New${TYPE_NAME} returns a disabled stub instance.
func New${TYPE_NAME}() *${TYPE_NAME} {
    enterprise.ObserveDisabled("${FEATURE_LABEL}")
    return &${TYPE_NAME}{}
}
STUB
    if [[ -n "$IFACE_NAME" ]]; then
      echo "var _ $IFACE_NAME = (*$TYPE_NAME)(nil)"
      echo
    fi
    cat <<'STUB'
// Example method template (delete/adjust):
func (s *REPLACE_TYPE) Example(ctx context.Context) error {
    enterprise.ObserveInvocation("REPLACE_FEATURE", false)
    enterprise.ObserveError("REPLACE_FEATURE", "disabled")
    return enterprise.DisabledError("REPLACE_FEATURE")
}
STUB
  } | sed "s/REPLACE_TYPE/${TYPE_NAME}/g; s/REPLACE_FEATURE/${FEATURE_LABEL}/g" > "$STUB_FILE"
fi

if [[ -f "$REAL_FILE" ]]; then
  echo "Skip (exists): $REAL_FILE" >&2
else
  echo "Creating enterprise scaffold: $REAL_FILE" >&2
  {
    echo "//go:build enterprise"; echo; header
    echo "package $(basename "$PKG_DIR")"; echo
    cat <<REAL
// ${TYPE_NAME} enterprise implementation scaffold.
// TODO: implement real logic. Replace Example method bodies and extend constructor.
type ${TYPE_NAME} struct{}

func New${TYPE_NAME}() *${TYPE_NAME} { return &${TYPE_NAME}{} }

// Example shows how to record an allowed invocation (remove when real methods added).
func (s *${TYPE_NAME}) Example(ctx context.Context) error {
    // enterprise.ObserveInvocation("${FEATURE_LABEL}", true) // optional latency histogram wrapper later
    return nil
}
REAL
  } > "$REAL_FILE"
fi

echo "Done." >&2
